# Generated by Django 5.2.9 on 2025-12-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_messages_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
