# Generated by Django 5.2.9 on 2025-12-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_options_remove_room_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='room_images/default_room.jpg', null=True, upload_to='room_images/'),
        ),
    ]
